name: Publish package to the Maven Central Repository

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      id: setup-jdk
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: GPG_SIGNING_KEY
        gpg-passphrase: GPG_SIGNING_PASSPHRASE
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PWD }}

    - name: Extract release version
      run: |
        export RELEASE_VERSION="${{ github.event.release.tag_name }}"
        echo "Release Version: $RELEASE_VERSION"
      id: extract_release_version

    - name: Maven build
      run: mvn clean package -Prelease

    - name: Publish to Maven Central
      if: success()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          mvn --no-transfer-progress --batch-mode deploy -DreleaseVersion=$RELEASE_VERSION
        else
          echo "Build failed. Skipping deployment to Maven Central."
        fi
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PWD }}
