name: Publish package to the Maven Central Repository

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-package: 'jdk'
        java-version: '11'
        check-latest: true
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: GPG_SIGNING_PASSPHRASE
        cache: 'maven'

    - name: Extract release version
      run: |
        export RELEASE_VERSION="${{ github.event.release.tag_name }}"
        echo "Release Version: $RELEASE_VERSION"
      id: extract_release_version

    - name: Build & Deploy
      run: mvn clean install -Ppipeline

    - name: Publish to Maven Central
      if: success()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          mvn -B clean deploy -Prelease -DreleaseVersion=$RELEASE_VERSION -DskipTests
        else
          echo "Build failed. Skipping deployment to Maven Central."
        fi
      env:
        GPG_SIGNING_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        GPG_SIGNING_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PWD }}
