name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Extract release version
        run: |
          export RELEASE_VERSION="${{ github.event.release.tag_name }}"
          echo "Release Version: $RELEASE_VERSION"
        id: extract_release_version

      - name: Publish package
        run: |
          mvn clean install

          # Conditionally deploy to Maven Central only on successful builds
          if [ ${{ job.status }} == 'success' ]; then
            mvn deploy -DreleaseVersion=$RELEASE_VERSION
          else
            echo "Build failed. Skipping deployment to Maven Central."
          fi
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
